ALTER TABLE estado_jogador ADD COLUMN IF NOT EXISTS ano_atual INTEGER DEFAULT 1;

ALTER TABLE cultura ADD COLUMN IF NOT EXISTS ano_disponivel INTEGER;
ALTER TABLE cultura ADD COLUMN IF NOT EXISTS dia_disponivel INTEGER;
ALTER TABLE cultura ADD COLUMN IF NOT EXISTS requer_desbloqueio BOOLEAN DEFAULT FALSE;
ALTER TABLE cultura ADD COLUMN IF NOT EXISTS local_venda_padrao VARCHAR(50);
ALTER TABLE cultura ADD COLUMN IF NOT EXISTS pode_ser_comprada BOOLEAN DEFAULT TRUE;